spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: nest
    password: java1234
    driver-class-name: oracle.jdbc.OracleDriver

server:
  port: 8095

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
